name: Metrics  
  
on:  
  # Schedule daily updates  
  schedule: [{cron: "0 0 * * *"}]  
  # (optional) Run workflow manually  
  workflow_dispatch:  
  # (optional) Run workflow when pushing on master/main  
  push: {branches: ["master", "main"]}  
  
jobs:  
  github-metrics:  
   runs-on: ubuntu-latest  
   environment:  
    name: production  
   permissions:  
    contents: write  
    #pull-requests: write  
   steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  
      with:  
       fetch-depth: 0  
  
    - name: Default metrics  
      uses: lowlighter/metrics@latest  
      with:  
       filename: metrics.base.svg  
       token: ${{ secrets.METRICS_TOKEN }}  
       base: header, activity, community, repositories, metadata  
  
    - name: GitHub Skyline  
      uses: lowlighter/metrics@latest  
      with:  
       filename: metrics.plugin.skyline.svg  
       token: NOT_NEEDED  
       base: ""  
       plugin_skyline: yes  
       plugin_skyline_year: 2020  
       plugin_skyline_frames: 6  
       plugin_skyline_quality: 1  
  
    - name: Repositories traffic  
      uses: lowlighter/metrics@latest  
      with:  
       filename: metrics.plugin.traffic.svg  
       token: ${{ secrets.METRICS_TOKEN }}  
       base: repositories  
       plugin_traffic: yes  
  
    - name: Commit metrics  
      uses: lowlighter/metrics@latest  
      with:  
       config_timezone: America/Edmonton  
       output_action: commit  
       comitter_branch: metrics-render  
       comitter_message: "chore: update metrics"  
       retries_output_action: 5  
       retries_delay_output_action: 120  
       token: ${{ secrets.METRICS_TOKEN }}
